name: deploy site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [7.16.0]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
        
      - name: set HOME_IS_GITHUB_PAGES field
        run: |
          echo "\nHOME_IS_GITHUB_PAGES=true" >> .env

      - name: build
        run: |
          echo .env && pnpm i && pnpm run build
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist